### ISSUE TITLE
rickshaw_rails v1.1.2

### ISSUE THREAD

**Issue by ebouchut** [logical42/rickshaw_rails#11]
First off, thank you for the gem.

I need an older version of rickshaw (1.1.2) in my Rails project and have a branch handy for this version.
Q1) Would you accept a pull-request for it?

Q2) Provided the gem d3-rails  version  2.10.3 exist, would you plan on using it instead of embedding d3.v2.js in rickshaw_rails?
This would mean:
  - removing d3.v2.js  from app/assets/javascripts
  - Adding a dependency in the gemspec
If you agree on this, I could submit a pull-request to d3-rails with version v2.10.3.
What is your take on this?

Thanks

**Comment by phillbaker** [comment]
Both sound great - if you could submit separate PRs, that'd be good.

I think for the older versions, we'd have to not merge to master to avoid
overwriting the current version, a separate branch like vX-stable would be
fine. I can definitely accept and release these.

**Comment by ebouchut** [comment]
I just made PR #12  for the first one: rickshaw_rails version 1.1.2.

**Comment by ebouchut** [comment]
I plan on submitting the other PR later on.
